Feature/as 321 Como moderador quiero ver anomalías de precios en los aportes sobre un producto en una tienda para mejorar la informacion del sitio
locompro/ci0128_23b_all_stars pull request #242
Opened 2023-12-02 06:12 UTC by Brandoxx

![screenshot](https://github.com/locompro/ci0128_23b_all_stars/assets/70549736/ccd57fcb-3685-4314-b1f0-7c1d6ef21be5)

Cambios de este tiquete:

Pages/Moderation.cshtml & Pages/Moderation.cshtml.cs
Services/AnomalyDetectionService.cs
Services/Tasks/FindPriceAnomaliesTask
Services/Domain/SubmissionService.cs
Services/Domain/ReportService.cs
Data/Repositories/ReportRepository.cs

2023-12-02 06:17 UTC, joseph97svk approved these changes
─────────────────██▌─███████▌────────
─────────────────███─██████████▌─────
───────────────▐─███████████████▌────
──────────────▐██████████████████▌───
──────────────▐███████████████████▌──
──────────────▐████████████████████──
──────────────█████████░░░█████████──
─────────────██████░░░▓░░░░▓░░░░███──
────────────▐█████░░░▓░░░░░░░░░░░██──
─────────────▐███░░░█████░░░░███░█▌──
─────────────█████░█░░░░░░█▓░░░░█▌───
─────────────█████░░░░░░░░░░░░░░░▌───
─────────────█░███░░░░█░░░░░▐▀▌░░▌───
────────▄▄▄──█░░█░░░░░█░░░░░▐▄▌░▓▌───
──────▐█░░░█─█░█░░░░░░░░░█░░░░░░░▌───
─────▐█░░░░█─▐▄▌▓░░░░░░░░░░░░▓░░░▌───
─────▐█░░░░█───▐▓░░░▐▄▄▄▄▄▄▄▄░░░█────
──────▐█░░░█▌───▐▓░░░▐─────▌░░░█▌────
──▄▄▄▄███░░██────▐▓░░░▀▀▀▀▀░░░█▌─────
─▐██░░████░░█▄▄───██▓░░░░░░░░█▌──────
▐██▓▓▓▓▓▓░░░░▓█▌─█████░░░░░▓██───────
▐█▓░░░░░░▓░░░░▓▓▌─███████████────────
▐█▓▓▓▓▓▓▓▓▓░░░█▓█▄▄█████▓▓██─────────
▐█▓░░░░░▓▓░░░░░░░▓▓▓████▓░███────────
▐█▓▓▓▓▓▓▓▓▓░█░░▓█▓▄██████░░███▄──────
─▐█░░░░░▓▓░██▀▀▀▀▐██████░▄░███▓▌─────
──▀▀▀▀▀▀▀▀▀▀──────█████░░▄░░███▓▌────
─────────────────▐█████░░▄░░██▓░▓▌───
─────────────────▐█████░░▄░░███░▓▌───
────────────────▐██████░░▄░░███░░▓▌──
─░░────────────▐███████░░▄░░███▓░▓▌──
░░░░───────────▐███████░░░▄░░░███░▓▌─
░──░──────────────▐████████████▌░░▓▌─
░──░──────────────█████████████▌▓░░▓▌
░──░─────────────▐██████████████░▓░▓▌
░──░─────────────███████████████▓░▓▌─
░──░──────────────▓████████████▌░▓▌──
░──░────────────────█▓█▌──█▓█▌───────
░──░────────────────█▓█▌──█▓█▌───────
░──░────────────────█▓█▌──█▓█▌───────
░──░────────────█──██▓█▌─█▓▓█████▓▌──
░──░───────█████████▓█▌─██▓▓███████▌─
░──░──────█████████▓▓▓█▌─████████───█
░░░░─────██───██████▓██▌──███████████
─░░─────██████████████▌───██──█████──
─────────████████──██

2023-12-02 06:17 UTC, arielarevalo approved these changes

2023-12-02 21:43 UTC, Antonio-Tresol requested changes
Dejé comentarios en AnomalyDetectionService.cs

2023-12-02 21:43 UTC, Antonio-Tresol commented on Source/Locompro/Services/AnomalyDetectionService.cs
> +    {
Si solo esta clase lo va utilizar GroupSubmission en esta clase, debería ser internal. Si se va utilizar en otro lado, sacarla de aquí.

2023-12-02 21:43 UTC, Antonio-Tresol commented on Source/Locompro/Services/AnomalyDetectionService.cs
> +            .ToList();
Cuando la query es tan grande, puede que sea más legible usar notación  funcion{ var result = query; return result } que usar funcion=>query

2023-12-03 17:49 UTC, GabrielMBulgarelli approved these changes

2023-12-03 23:27 UTC, merged