Feature/as 17 Refactorizando código de inicio de sesión en servicios.
locompro/ci0128_23b_all_stars pull request #26
Opened 2023-09-28 05:27 UTC by Antonio-Tresol

2023-09-28 18:23 UTC, arielarevalo commented on Locompro/Areas/Identity/Pages/Account/Login.cshtml.cs
> +        private readonly UserService userService;
Class fields van con mayúscula en .NET (al parecer :v)

2023-09-28 18:27 UTC, arielarevalo commented on Locompro/Services/UserService.cs
>      public class UserService : AbstractService<User, string, UserRepository>
Me parece que lo mejor es separar las capas de aplicación y la de dominio. 

UserService se ocupa de operaciones sobre entidades service que cumplan con las reglas del negocio una vez que ya los datos están en la aplicación.

AuthService se ocupa del manejo de sesiones y el instanciamiento de nuevos pares de autenticación a nivel de la aplicación.

2023-09-28 18:27 UTC, arielarevalo requested changes
Por favor revisar mis comentarios en el PR.

2023-10-01 03:23 UTC, joseph97svk commented on Locompro/Services/AuthService.cs
> +            var user = CreateUser();
aunque sea obvio el tipo por el contexto, preferiria si definiera el tipo. Seguridad de tipos evita problemas

2023-10-01 03:23 UTC, joseph97svk approved these changes

2023-10-01 21:10 UTC, closed without merging