Feature/as 4 Se abstrae la lógica de negocios a UserService. Se crea RegisterViewModel
locompro/ci0128_23b_all_stars pull request #27
Opened 2023-09-28 14:54 UTC by Brandoxx

2023-09-28 18:31 UTC, arielarevalo requested changes
Lo mismo que en el PR de Antonio. Mejor separar en dos servicios autenticación y las operaciones sobre entidades usuarios de forma AuthService/UserService

2023-10-01 03:25 UTC, joseph97svk commented on Locompro/Areas/Identity/Pages/Account/Login.cshtml.cs
> -                var result = await _signInManager.PasswordSignInAsync(Input.Email, Input.Password, Input.RememberMe, lockoutOnFailure: false);
considerar beneficios de colocar tipo de variable en todo momento

2023-10-01 03:25 UTC, joseph97svk approved these changes

2023-10-01 23:25 UTC, arielarevalo approved these changes

2023-10-01 23:25 UTC, merged